<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Actions' => '',
  'Advanced Search' => '',
  'Are you sure you want to delete this item?' => '',
  'Categories' => '',
  'Category' => '',
  'Create' => '',
  'Create Category' => '',
  'Create Language' => '',
  'Create Page' => '',
  'Create Photo' => '',
  'Create Time' => '',
  'Create Tool' => '',
  'Create Work' => '',
  'Create new' => '',
  'Delete Category' => '',
  'Delete Language' => '',
  'Delete Photo' => '',
  'Delete Tool' => '',
  'Email' => '',
  'File' => '',
  'Id' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Label' => '',
  'Languages' => '',
  'Link' => '',
  'List Work' => '',
  'Manage' => '',
  'Manage Categories' => '',
  'Manage Category' => '',
  'Manage Language' => '',
  'Manage Languages' => '',
  'Manage Page' => '',
  'Manage Pages' => '',
  'Manage Photo' => '',
  'Manage Photos' => '',
  'Manage Tool' => '',
  'Manage Tools' => '',
  'Manage Work' => '',
  'Manage Works' => '',
  'Media' => '',
  'Name' => '',
  'Object' => '',
  'Pages' => '',
  'Parent' => '',
  'Parent Url' => '',
  'Password' => '',
  'Password is incorrect.' => '',
  'Photos' => '',
  'Relative Path' => '',
  'Remember me next time' => '',
  'Role' => '',
  'Save' => '',
  'Search' => '',
  'Sorting' => '',
  'Tool' => '',
  'Tools' => '',
  'Type' => '',
  'Type data in' => '',
  'Update' => '',
  'Update Category' => '',
  'Update Language' => '',
  'Update Object Info' => '',
  'Update Page Info' => '',
  'Update Tool' => '',
  'Update WorkInfo' => '',
  'Url' => '',
  'User Name' => '',
  'User not found' => '',
  'Username' => '',
  'Username is incorrect.' => '',
  'View Category' => '',
  'View Info' => '',
  'View Language' => '',
  'View Page' => '',
  'View Photo' => '',
  'View Tool' => '',
  'View Work' => '',
  'Work' => '',
  'Works' => '',
  'Delete Work' => '',
  'Update Work' => '',
);
