<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Id' => '',
  'Delete Work' => 'Удалить работу',
  'Update Work' => 'Обновить работу',
  'Actions' => 'Действия',
  'Advanced Search' => 'Поиск',
  'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
  'Categories' => 'Категории',
  'Category' => 'Категория',
  'Create' => 'Создать',
  'Create Category' => 'Создать категорию',
  'Create Language' => 'Создать язык',
  'Create Page' => 'Создать страницу',
  'Create Photo' => 'Создать фото',
  'Create Time' => 'Дата создания',
  'Create Tool' => 'Создать инструмент',
  'Create Work' => 'Создать работу',
  'Create new' => 'Создать новый/новую',
  'Delete Category' => 'Удалить категорию',
  'Delete Language' => 'Удалить язык',
  'Delete Photo' => 'Удалить фото',
  'Delete Tool' => 'Удалить инструмент',
  'Email' => 'Почта',
  'File' => 'Файл',
  'First Name'       => 'Имя',  
  'Forgot your password?' => 'Напомнить Ваш пароль?',
  'Invalid request. Please do not repeat this request again.' => 'Некорректный запрос. Пожалуйста, не повторяйте его.',
  'Label' => 'Метка',
  'Languages' => 'Языки',
  'Link' => 'Ссылка',
  'List Work' => 'Список работ',
  'Manage' => 'Управление',
  'Manage Categories' => 'Управление категориями',
  'Manage Category' => 'Управление категориями',
  'Manage Language' => 'Управление языками',
  'Manage Languages' => 'Управление языками',
  'Manage Page' => 'Управление страницами',
  'Manage Pages' => 'Управление страницами',
  'Manage Photo' => 'Управление фотографией',
  'Manage Photos' => 'Управление фотографиями',
  'Manage Tool' => 'Управление инструментами',
  'Manage Tools' => 'Управление инструментами',
  'Manage Work' => 'Управление работами',
  'Manage Works' => 'Управление работами',
  'Media' => 'Медиа',
  'Name' => 'Имя',
  'Object' => 'Объект',
  'Pages' => 'Страницы',
  'Parent' => 'Родитель',
  'Parent Url' => 'Родительский адрес',
  'Password' => 'Пароль',
  'Password is incorrect.' => 'Неверный пароль',
  'Photos' => 'Фотографии',
  'Post comment' => 'Комментировать',
  'Relative Path' => 'Относительный путь',
  'Remember me' => 'Запомнить меня',  
  'Remember me next time' => 'Запомнить меня',
  'Role' => 'Роль',
  'Save' => 'Сохранить',
  'Search' => 'Поиск',
  'Sorting' => 'Сортировка',
  'Submit' => 'Передать',
  'Tool' => 'Инструмент',
  'Tags' => 'Теги',
  'Tools' => 'Инструменты',
  'Type' => 'Тип',
  'Type data in' => 'Введите данные на',
  'Update' => 'Обновить',
  'Update Category' => 'Обновить категорию',
  'Update Language' => 'Обновить язык',
  'Update Object Info' => 'Обновить информацию об объекте',
  'Update Page Info' => 'Обновить информацию о странице',
  'Update Tool' => 'Обновить инструмент',
  'Update WorkInfo' => 'Обносить информацию о работе',
  'Url' => 'Адрес',
  'User Name' => 'Имя пользователя',
  'User not found' => 'Пользователь не найден',
  'Username' => 'Имя пользователя',
  'Username is incorrect.' => 'Неверное имя пользователя',
  'View Category' => 'Просмотреть категорию',
  'View Info' => 'Просмотреть информацию',
  'View Language' => 'Просмотреть язык',
  'View Page' => 'Просмотреть страницу',
  'View Photo' => 'Просмотреть фото',
  'View Tool' => 'Просмотреть инструмент',
  'View Work' => 'Просмотреть работу',
  'We use' => 'Мы используем',
  'We work whis:' => 'Мы работаем с:',
  'Work' => 'Работа',
  'Works' => 'Работы',
);
