<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Entry' => 'Войти',
  'Registration' => 'Регистрация',
  'Login' => 'Войти',
  'Password' => 'Пароль',
  'Confirm password' => 'Подтверждение пароля',
  'Wrong personal code given' => 'Неверный код восстановления пароля',
  'User not verified' => 'Аккаунт не активирован',
  'No such user found' => 'Пользователь не найден',
  'Forgot your password?' => 'Забыли пароль?',
  'Registration' => 'Регистрация',
  'Register' => 'Готово',
  'Password recovery' => 'Восстановление пароля',
  'Password change' => 'Изменение пароля',
  'Password confirmed incorrectly!' => 'Пароль подтвержден неверно',
  'Okay' => 'Готово',
  'You account was registered. Please check your email address and complete account activation.' => 'Ваш аккаунт зарегистрирован. Пожалуйста, проверьте вашу почту и активируйте профиль.',
  'User has been activated. You are able to {LOGIN}.' => 'Ваш аккаунт активирован успешно. Вы можете {LOGIN} на сайт.',
  'login' => 'авторизоваться',
  'Activation user error.' => 'Ошибка активации аккаунта',
  'User already activated.' => 'Аккаунт уже активирован.',
  'Bad Request' => 'Неверный запрос',
  'Activation email error.' => 'Ошибка подтверждения почтового адреса.',
  'Email already activated.' => 'Почтовый адрес уже был подтвержден.',
  'Password recovery message sent. Check your email, please.' => 'Письмо со ссылкой на восстановление пароля отправлено вам на почту.',
  'Incorrect email or password.' => 'Неверный email или пароль',
  'Email not verified.' => 'Аккаунт не активирован',
  'Password changed successfully.' => 'Пароль успешно изменен.',
);