<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Account activation' => 'Активация аккаунта',
  'Congradulations! You was registered on our site' => 'Поздравляем! Вы зарегистрированы на нашем сайте',
  'Please activate your account before authorization.' => 'Пожалуйста активируйте ваш аккаунт перед авторизацией. ',
  'Your activation link is' => 'Ваша ссылка активации ',
  'Activated URL' => 'URL Активации',
  'Please confirm your email address, go to {LINK}.' => 'Пожалуйста, подтвердите свой адрес электронной почты, перейдите по {LINK}',
  'The password recovery procedure for a user with this email ({EMAIL}) was initiated on our site.' => 'Процедура восстановления пароля для пользователя с этой электронной почты ({EMAIL}) была инициирована на нашем сайте. ',
  'Your password change link is' => 'Ссылка изменения вашего пароля',
  'Thanks for posting. Your password: {PASSWORD}.' => 'Спасибо за запись. Ваш пароль: {PASSWORD}.',
  'Password change' => 'Изменение пароля',
 );

