<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Web'             => 'Web',               // 'Веб'
  'Desktop'         => 'Desktop',           //'Рабочее окружение'
  'Mobile'          => 'Mobile',            //'Мобильныe приложения'
  'Developer Tools' => 'Developer Tools',   //'Инструменты разработчика'
  'About Us'        => 'О нас',             //
  'Administration'  => 'Administration',    //'Администрирование'
  'All Posts'       => 'Все Статьи',         //'Все статьи'
  'Login' => 'Войти',
  'Phone' => 'Телефон',
  'Skype' => 'Скайп',
  'Email' => 'Почта',
  'Twitter' => 'Твиттер',
  'Home'=>'Главная',
  'About'=>'О Нас',
  'Our Project' => 'Наши проекты',
  'Our Services' =>' Наши проекты',
  'Blog'=>'Блог',
  
);
